# Generated by Django 4.2 on 2023-05-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_currentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
