# Generated by Django 4.2 on 2023-05-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_product_categories_remove_product_price_and_more'),
    ]

    operations = [
    ]
