# Generated by Django 4.2 on 2023-05-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_store_products_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products1',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product'),
        ),
    ]
