# Generated by Django 4.2.1 on 2023-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainApp', '0009_remove_store_products1_store_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=150)),
                ('receiver', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('read', 'read')], default='pending', max_length=10)),
            ],
        ),
    ]
