# Generated by Django 4.2.1 on 2023-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0010_alter_member_password_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("message", "message"), ("notification", "notification")],
                default="notification",
                max_length=100,
            ),
        ),
    ]
