# Generated by Django 4.2.1 on 2023-05-13 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_usermessage_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 13, 20, 19, 47, 803272, tzinfo=datetime.timezone.utc)),
        ),
    ]
