# Generated by Django 4.2.1 on 2023-05-14 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_usermessage_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 14, 6, 33, 26, 582169, tzinfo=datetime.timezone.utc)),
        ),
    ]
