# Generated by Django 4.2.1 on 2023-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_usermessage_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
