# Generated by Django 4.2.1 on 2023-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_usermessage_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
